export const growthSnapshot = Object.freeze({
  schema: 1,
  account: '@BkashJosi',
  verifiedAt: '2026-07-22',
  analyticsCoverage: '2026-04-14 to 2026-07-12',
  auditCoverage: '2026-07-18 to 2026-07-21',
  mission: { current: 185, target: 10000, remaining: 9815, progress: 1.85 },
  gate: { score: 67, maximum: 100, decision: 'HOLD' },
  baseline: {
    posts: 72, postsPerDay: 18, views: 6434, averageViews: 89.4,
    medianViews: 61, publicInteractions: 37, interactionRate: 0.58,
    zeroActionRate: 66.7,
  },
  focus: [
    'Publish no more than four original posts per day.',
    'Space original posts at least three hours apart.',
    'Lead with a problem, mechanism, and real proof.',
    'Use one conversion path per post.',
  ],
  formats: [
    { name: 'Articles', posts: 25, views: 3410, average: 136.4, rate: 0.35, index: 2.53, job: 'Discovery', decision: 'Keep, then distribute once.' },
    { name: 'Quote posts', posts: 18, views: 1592, average: 88.4, rate: 0.75, index: 1.64, job: 'Context', decision: 'Use only when adding a new mechanism or test.' },
    { name: 'Image / link', posts: 25, views: 1350, average: 54, rate: 0.96, index: 1, job: 'Proof', decision: 'Use receipts, diagrams, and screenshots.' },
    { name: 'Text only', posts: 4, views: 82, average: 20.5, rate: 0, index: 0.38, job: 'Fast thought', decision: 'Avoid generic wrappers.' },
  ],
  gateDimensions: [
    { name: 'Eligibility / trust', score: 9, max: 10, status: 'Strong' },
    { name: 'Audience / retrieval fit', score: 7, max: 15, status: 'Weak' },
    { name: 'In-feed value', score: 11, max: 15, status: 'Good' },
    { name: 'Evidence discipline', score: 12, max: 15, status: 'Strong' },
    { name: 'Hook integrity', score: 7, max: 10, status: 'Good' },
    { name: 'Satisfaction / action design', score: 4, max: 10, status: 'Critical' },
    { name: 'Negative-feedback prevention', score: 6, max: 10, status: 'Weak' },
    { name: 'Freshness / diversity', score: 4, max: 10, status: 'Critical' },
    { name: 'Media utility', score: 4, max: 5, status: 'Strong' },
    { name: 'Experiment discipline', score: 3, max: 5, status: 'Weak' },
  ],
  milestones: [
    ['Now', 185, 'Baseline'], ['Month 1', 350, 'Signal'], ['Month 2', 600, 'Signal'],
    ['Month 3', 1000, 'Authority'], ['Month 4', 1600, 'Authority'], ['Month 5', 2400, 'Authority'],
    ['Month 6', 3400, 'Distribution'], ['Month 7', 4600, 'Distribution'], ['Month 8', 5900, 'Distribution'],
    ['Month 9', 7200, 'Conversion'], ['Month 10', 8400, 'Conversion'], ['Month 11', 9300, 'Conversion'],
    ['Month 12', 10000, '10K'],
  ],
  experiment: {
    id: 'XG-20260722-001', sample: '12 posts / 3 days',
    hypothesis: 'Four proof-led posts per day, spaced at least three hours apart, will beat the current typical post.',
    baseline: 'Median 61 views · 0.58% observed interaction rate',
    variable: 'Posting cadence + proof requirement',
  },
  competitors: [
    { handle: '@BkashJosi', tier: 'Own', followers: 185, note: 'Hermes/OpenClaw operator intelligence.' },
    { handle: '@arknow91', tier: 'Peer signal', followers: 754, note: 'One verified visual-proof signal; not a complete competitor baseline.' },
    { handle: '@NousResearch', tier: 'Source', followers: null, note: 'Primary Hermes and open-model releases.' },
    { handle: '@OpenClaw', tier: 'Source', followers: null, note: 'Primary product proof; avoid brand confusion.' },
    { handle: '@simonw', tier: 'Aspirational', followers: null, note: 'High-signal tooling experiments and research notes.' },
    { handle: '@levelsio', tier: 'Aspirational', followers: null, note: 'One-person business proof; never repeat unverified revenue claims.' },
  ],
  rawAnalytics: {
    rows: 362,
    status: 'Verified first-party export; stale after July 12.',
    latest: [
      { date: 'Jul 12', text: 'This is really one cool skill that your Hermes agent should learn.', impressions: 24, engagements: 0 },
      { date: 'Jul 12', text: 'Tf. X', impressions: 18, engagements: 2 },
      { date: 'Jul 11', text: 'What are your hardware specs for this?', impressions: 33, engagements: 3 },
      { date: 'Jul 10', text: 'Custom Device for Hermes. No more traditional gateway.', impressions: 31, engagements: 0 },
    ],
  },
  metrics: [
    ['Follower growth', 'End followers − start followers', 'Weekly'],
    ['Median views / post', 'Median visible views in the same class and window', '24h / 72h'],
    ['Observed interaction rate', 'Visible interactions ÷ public views', '24h / 72h'],
    ['Private engagement rate', 'X engagements ÷ impressions', 'Weekly export'],
    ['Zero-action rate', 'Posts with zero visible actions ÷ posts', 'Weekly'],
    ['Posting frequency', 'Canonical posts ÷ active days', 'Daily'],
  ],
  sources: [
    { item: 'Current followers', value: '185', status: 'Verified', source: 'Live X profile · Jul 22' },
    { item: '4-day audit sample', value: '72 posts', status: 'Verified', source: 'Public profile audit · Jul 18–21' },
    { item: 'Historical analytics', value: '362 rows', status: 'Verified', source: 'Native X export · through Jul 12' },
    { item: 'Algorithm decision', value: 'HOLD · 67/100', status: 'Verified', source: 'Editorial operating gate' },
    { item: '10K monthly path', value: 'Planning targets', status: 'Assumption', source: '10K Growth Plan' },
  ],
  workbookMap: [
    ['Executive Dashboard', 'Today'], ['Format Analysis', 'Posts'], ['Algorithm Gate', 'Today / More'],
    ['Post Tracker', 'Posts'], ['Competitor Tracker', 'Intel'], ['10K Growth Plan', 'Plan'],
    ['Experiment Tracker', 'Plan'], ['Raw Analytics to Jul12', 'Posts'], ['Metric Dictionary', 'More'],
    ['Sources & Decisions', 'More'],
  ],
});
