export const operatorWorkbench = {
  schema: 1,
  product: 'Operator Workbench',
  release: 'MVP · read-only',
  mission: 'Turn verified signals into safe, repeatable outcomes.',
  loop: ['Signal', 'Playbook', 'Evidence', 'Approval', 'Result'],
  surfaces: [
    {
      id: 'token-pulse',
      name: 'Token Pulse',
      role: 'Runtime intelligence',
      state: 'Private telemetry ready',
      href: '/',
      note: 'Owns token, runtime, session, freshness, and resource-pressure evidence.',
    },
    {
      id: 'growth-command',
      name: 'Growth Command',
      role: 'Experiment system',
      state: 'Verified snapshot connected',
      href: '/growth',
      note: 'Owns X mission, content evidence, experiment status, and measured growth results.',
    },
    {
      id: 'operator-workbench',
      name: 'Operator Workbench',
      role: 'Outcome orchestration',
      state: 'MVP · read-only',
      href: '/operator',
      note: 'Owns triggers, operating contracts, proof requirements, and approval boundaries.',
    },
  ],
  playbooks: [
    {
      id: 'morning-operator-brief',
      category: 'Work',
      title: 'Start with one decision-ready brief',
      outcome: 'Convert runtime pressure and growth priorities into one ranked move for today.',
      trigger: 'First work session of the day or after a major context switch.',
      cadence: 'Daily · manual in MVP',
      integrations: ['Token Pulse', 'Growth Command', 'Hermes'],
      sources: ['Latest privacy-redacted Token Pulse snapshot', 'Current Growth Command experiment and source ledger'],
      steps: ['Check data freshness before using any metric.', 'Separate observed facts from assumptions.', 'Rank one move by impact, confidence, and reversibility.', 'Name the proof that will close the loop.'],
      approval: 'Required only if the selected move sends, publishes, spends, deletes, or changes an external system.',
      proof: 'A one-page brief with source timestamps, one owner, one move, and one acceptance check.',
      success: 'Dad can approve, reject, or redirect the move in under two minutes.',
      prompt: 'Build today’s operator brief from the latest Token Pulse and Growth Command evidence. Separate observed facts, source claims, inference, and unknowns. Recommend exactly one highest-leverage reversible move. Include source freshness, owner, approval gate, and the real artifact or system check that proves completion. Do not send, publish, spend, delete, or change an external system without Dad’s fresh approval.',
    },
    {
      id: 'session-runway',
      category: 'Work',
      title: 'Protect context before it becomes drag',
      outcome: 'Detect bloated or stale sessions and preserve only the decisions worth carrying forward.',
      trigger: 'Token Pulse reports high session usage, stale work, or repeated context switching.',
      cadence: 'On signal · manual in MVP',
      integrations: ['Token Pulse', 'Hermes session history'],
      sources: ['Aggregate session usage only', 'Current task and completion evidence'],
      steps: ['Identify the largest active context without reading private prompt text.', 'Separate completed work from unresolved decisions.', 'Write a compact handoff with proof links.', 'Start fresh only when the old context no longer changes the next move.'],
      approval: 'No approval for a local draft; Dad approves destructive session cleanup.',
      proof: 'A handoff containing outcome, verified state, blockers, decisions, and next action.',
      success: 'The next session can continue without re-reading irrelevant history.',
      prompt: 'Review the current work using privacy-bounded session totals and task evidence. Do not inspect or reproduce private prompt text. Produce a compact handoff containing the goal, completed evidence, unresolved decisions, blockers, and one next action. Recommend a fresh session only when prior context no longer changes the work. Do not delete history without Dad’s approval.',
    },
    {
      id: 'growth-experiment-review',
      category: 'Work',
      title: 'Decide the next growth experiment',
      outcome: 'Turn X performance evidence into one falsifiable experiment instead of more posting volume.',
      trigger: 'An experiment reaches its evidence window or current analytics are refreshed.',
      cadence: 'Weekly · manual in MVP',
      integrations: ['Growth Command', 'X Analytics', 'PulseMark'],
      sources: ['Canonical post tracker', 'Native analytics export', 'PulseMark pain-point record'],
      steps: ['Confirm the analytics window and sample size.', 'Compare like-for-like formats and jobs.', 'Change one variable only.', 'Define a stop, continue, or scale threshold before publishing.'],
      approval: 'Dad approves publishing and any outreach. Analysis and drafts are read-only.',
      proof: 'Experiment ID, hypothesis, single variable, baseline, target window, and decision rule.',
      success: 'A result can be attributed to one intentional change rather than posting noise.',
      prompt: 'Using the latest Growth Command evidence and a referenced PulseMark pain-point ID, define one X experiment. Verify the analytics window, compare like-for-like formats, change one variable, and state the hypothesis, baseline, sample size, success threshold, stop rule, and follow-up measurement. Draft only; publishing requires Dad’s approval.',
    },
    {
      id: 'proof-led-content',
      category: 'Work',
      title: 'Turn a signal into proof-led content',
      outcome: 'Ship a credible post package grounded in a real source and a tested takeaway.',
      trigger: 'A verified product update, user pain, or local test produces a useful finding.',
      cadence: 'On verified signal',
      integrations: ['Growth Command', 'PulseMark', 'Official docs/repos'],
      sources: ['Primary source', 'Local test or direct artifact', 'PulseMark pain-point record'],
      steps: ['Verify the claim at the primary source.', 'Reproduce or test the practical point when possible.', 'Write the lead under 280 characters.', 'Package visual direction and define the measurement window.'],
      approval: 'Dad must approve every public post, comment, reply, or DM.',
      proof: 'Source URL, local result or explicit limitation, final post package, and measurement plan.',
      success: 'The post teaches one concrete move and can be audited back to evidence.',
      prompt: 'Create an X-only proof-led content package from the supplied verified signal. Reference the PulseMark pain-point ID, inspect the primary source, label what was observed versus documented or inferred, and include a sharp lead of at most 280 characters, media direction, CTA, follow-up comment, and measurement window. Do not publish until Dad explicitly approves the final package.',
    },
    {
      id: 'weekly-business-catchup',
      category: 'Work',
      title: 'Catch up across the business without reading everything',
      outcome: 'Compress projects, experiments, and blockers into decisions rather than activity summaries.',
      trigger: 'End of week, return from leave, or more than three active workstreams.',
      cadence: 'Weekly',
      integrations: ['Hermes tasks', 'Token Pulse', 'Growth Command', 'Obsidian'],
      sources: ['Current task ledger', 'Verified artifacts and receipts', 'Latest product snapshots'],
      steps: ['List only work with a real artifact, receipt, or blocker.', 'Group by outcome instead of app.', 'Call out stale evidence and missing owners.', 'Recommend no more than three decisions.'],
      approval: 'Local synthesis is safe; external follow-ups require Dad’s approval.',
      proof: 'Decision brief with outcome, evidence, risk, owner, and next move.',
      success: 'No completed claim relies on agent self-report alone.',
      prompt: 'Produce a weekly business catch-up organized by outcomes, not tools. Include only work backed by a file, test, live URL, ID, screenshot, receipt, or explicit blocker. Mark stale or unverified claims. Surface no more than three decisions with one owner each, approval boundaries, and the smallest next move.',
    },
    {
      id: 'feedback-to-skill',
      category: 'Work',
      title: 'Turn repeated corrections into a reusable skill',
      outcome: 'Stop paying the same steering cost twice.',
      trigger: 'Dad corrects the same behavior twice or a non-trivial workflow succeeds after iteration.',
      cadence: 'On repeated evidence',
      integrations: ['Hermes skills', 'Session history'],
      sources: ['Correction examples', 'Successful command/tool evidence', 'Current skill content'],
      steps: ['Find the repeated correction and the successful pattern.', 'Separate stable procedure from temporary task state.', 'Add exact steps, pitfalls, and verification.', 'Test the skill on a bounded example.'],
      approval: 'Ask Dad before creating or deleting a skill; patching an already-used stale skill is allowed.',
      proof: 'Updated skill file plus a bounded verification result.',
      success: 'The next matching task needs less steering and preserves the same evidence standard.',
      prompt: 'Inspect recent session evidence for a repeated correction or a difficult workflow that now has a proven path. Propose a reusable skill containing triggers, prerequisites, exact steps, pitfalls, approval gates, and verification. Exclude temporary task progress and credentials. Ask Dad before creating or deleting the skill.',
    },
    {
      id: 'leave-the-desk-safely',
      category: 'Personal',
      title: 'Leave the desk without leaving risk behind',
      outcome: 'Pause at a clean checkpoint with private systems protected and work recoverable.',
      trigger: 'Dad is leaving the workstation or ending a long operator session.',
      cadence: 'On departure',
      integrations: ['Windows', 'Hermes task state', 'Local artifacts'],
      sources: ['Current running-process state', 'Unsaved work indicators', 'Task handoff'],
      steps: ['Check for bounded jobs that still need to finish.', 'Save a compact task handoff.', 'Confirm no approval or credential screen is exposed.', 'Lock Windows only when Dad has asked or stated he is away.'],
      approval: 'Locking is allowed when Dad is away; do not terminate valuable work without approval.',
      proof: 'Saved handoff and confirmed workstation lock state.',
      success: 'Dad can return without lost work or exposed private information.',
      prompt: 'Prepare a safe leave-the-desk checkpoint. Inspect bounded running jobs, preserve unfinished work in a compact handoff, confirm no credential or approval screen is exposed, and identify anything that would be lost by termination. Lock Windows only if Dad has said he is leaving or away. Do not terminate valuable work without approval.',
    },
    {
      id: 'personal-admin-window',
      category: 'Personal',
      title: 'Clear personal admin with one bounded window',
      outcome: 'Sort routine obligations without turning the day into inbox maintenance.',
      trigger: 'A planned personal-admin block or an overdue-item signal.',
      cadence: 'Weekly · manual in MVP',
      integrations: ['Calendar', 'Inbox', 'Documents'],
      sources: ['Dad-authorized account views only', 'Current due dates and confirmations'],
      steps: ['Identify time-sensitive items first.', 'Separate read-only review from consequential actions.', 'Draft responses or forms locally.', 'Ask for approval before sending, paying, purchasing, or changing an account.'],
      approval: 'Required for messages, payments, purchases, subscriptions, permissions, and account changes.',
      proof: 'A short action list with due date, draft or receipt, and approval status.',
      success: 'Time-sensitive obligations are handled without unapproved external actions.',
      prompt: 'Review the Dad-authorized personal admin sources for time-sensitive obligations. Separate observed due dates and confirmations from assumptions. Draft the smallest action list and prepare local drafts. Do not send messages, pay, purchase, subscribe, or change account settings without Dad’s fresh approval.',
    },
  ],
};
